-- AlterTable
ALTER TABLE "client" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "local" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "people" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
